export enum CancellationReason {
    APPOINTMENT_NO_LONGER_NEEDED = 'APPOINTMENT_NO_LONGER_NEEDED',
    PET_OWNER_NO_LONGER_AVAILABLE = 'PET_OWNER_NO_LONGER_AVAILABLE',
    PET_OWNER_NEEDS_TO_RESCHEDULE = 'PET_OWNER_NEEDS_TO_RESCHEDULE',
    OTHER = 'OTHER',
}