export enum Status {
  UPCOMING = 'UPCOMING',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
  WAITING_FOR_CONFIRMATION = 'WAITING_FOR_CONFIRMATION',
}
