version: "3.9"

services:
  angular-frontend:
    image: angular-frontend
    container_name: angular-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
    ports:
      - "4200:4200"
    volumes:
      - ./public:/app/public
