  export enum AppRoutePaths {
    Default = '/',
    Review = '/reviews',
    UpdateReview = '/updateReview/:reviewId/edit',
    Form = '/forms',
    Inventories = '/inventories',
    Vet = '/vets',
    InventoryProducts = '/inventory/:inventoryId/products',
    CustomerBills = '/bills/customer',
    PageNotFound = '/page-not-found',
    Unauthorized = '/unauthorized',
    RequestTimeout = '/request-timeout',
    InternalServerError = '/internal-server-error',
    ServiceUnavailable = '/service-unavailable',
    login = '/users/login',
    CustomerProfileEdit = '/customer/profile/edit',
    AddingCustomer = '/customer/add',
    AllCustomers = '/customers',
    Home = '/home',
    Forbidden = '/forbidden',
    Products = '/products',
    Visits = '/visits',
    VetDetails ='/vets/{vetId}'
  }