CREATE DATABASE IF NOT EXISTS 'auth' DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE USERS(
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(2048) NOT NULL UNIQUE,
    username VARCHAR(2048) NOT NULL,
    password VARCHAR(2048) NOT NULL
);