CREATE DATABASE IF NOT EXISTS `auth`;

CREATE TABLE USERS(
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(2048) NOT NULL UNIQUE,
    username VARCHAR(2048) NOT NULL,
    password VARCHAR(2048) NOT NULL,
    PRIMARY KEY(id)
);