---
server:
  error:
    include-message: always
  logging:
    level:
      root: INFO
      com.petclinic: DEBUG

spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      port: 0
      database: customers
  mongodb:
    embedded:
      version: 4.0.21

app:
  files-service:
    host: localhost
    port: 8000

---
spring:
  config:
    activate:
      on-profile: integration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customers
      username: root
      password: password
      authentication-database: admin

app:
  files-service:
    host: localhost
    port: 8000
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo-customers
      port: 27017
      database: customers
      username: root
      password: password
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
app:
  files-service:
    host: files-service
    port: 8000
