global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-services"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "auth-service:8080" # auth-service

