server.port: 7006

logging:
  level:
    root: INFO
    com.petclinic: DEBUG


spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      port: 0
      database: inventories
de.flapdoodle.mongodb.embedded.version: 5.0.5

---
spring:
  config:
    activate:
      on-profile: integration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: inventory
      username: root
      password: password
      authentication-database: admin
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo-vet
      port: 27017
      database: inventory
      username: root
      password: password
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus