---
server:
  port: 7007

  error:
    include-message: always

logging:
  level:
    root: INFO
    com.petclinic: DEBUG

spring:
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: default

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/products
    username: user
    password: pwd

---
# tests

spring:
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: test

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/products
    username: user
    password: pwd
---
#docker
spring:
  codec:
    max-in-memory-size: 16MB
  config:
    activate:
      on-profile: docker

  r2dbc:
    url: r2dbc:postgresql://postgres-products:5432/products
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server.port: 8080
