CREATE TABLE IF NOT EXISTS products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          VARCHAR(36) NOT NULL UNIQUE,
    image_id            VARCHAR(36),
    product_name        TEXT,
    product_description TEXT,
    product_sale_price  DOUBLE PRECISION,
    average_rating      DOUBLE PRECISION,
    request_count       INTEGER,
    product_quantity    INTEGER,
    is_unlisted         BOOLEAN,
    product_type        TEXT,
    product_type_id     VARCHAR(36),
    release_date        DATE,
    product_status      TEXT,
    delivery_type       TEXT
);


-- CPC-1937: additive upgrade for existing databases (schema.sql runs on startup).
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_name_fr TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_description_fr TEXT;

-- Backfill only unchanged seeded text; never overwrite employee translations.
UPDATE products SET product_name_fr = 'Nourriture pour chiens'
WHERE product_id = '06a7d573-bcab-4db3-956f-773324b92a80' AND product_name = 'Dog Food' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Nourriture sèche de qualité supérieure pour chiens adultes'
WHERE product_id = '06a7d573-bcab-4db3-956f-773324b92a80' AND product_description = 'Premium dry food for adult dogs' AND product_description_fr IS NULL;
UPDATE products SET product_name_fr = 'Litière pour chats'
WHERE product_id = '98f7b33a-d62a-420a-a84a-05a27c85fc91' AND product_name = 'Cat Litter' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Litière agglomérante pour chats avec contrôle des odeurs'
WHERE product_id = '98f7b33a-d62a-420a-a84a-05a27c85fc91' AND product_description = 'Clumping cat litter with odor control' AND product_description_fr IS NULL;
UPDATE products SET product_name_fr = 'Collier antipuces'
WHERE product_id = 'baee7cd2-b67a-449f-b262-91f45dde8a6d' AND product_name = 'Flea Collar' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Protection contre les puces et les tiques pour petits chiens'
WHERE product_id = 'baee7cd2-b67a-449f-b262-91f45dde8a6d' AND product_description = 'Flea and tick prevention for small dogs' AND product_description_fr IS NULL;
UPDATE products SET product_name_fr = 'Cage pour oiseaux'
WHERE product_id = 'ae2d3af7-f2a2-407f-ad31-ca7d8220cb7a' AND product_name = 'Bird Cage' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Cage spacieuse pour petits oiseaux comme les perruches'
WHERE product_id = 'ae2d3af7-f2a2-407f-ad31-ca7d8220cb7a' AND product_description = 'Spacious cage for small birds like parakeets' AND product_description_fr IS NULL;
UPDATE products SET product_name_fr = 'Filtre pour aquarium'
WHERE product_id = '4d508fb7-f1f2-4952-829d-10dd7254cf26' AND product_name = 'Aquarium Filter' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Système de filtration pour aquariums de petite et moyenne taille'
WHERE product_id = '4d508fb7-f1f2-4952-829d-10dd7254cf26' AND product_description = 'Filter system for small to medium-sized aquariums' AND product_description_fr IS NULL;
UPDATE products SET product_name_fr = 'Selle pour cheval'
WHERE product_id = 'a6a27433-e7a9-4e78-8ae3-0cb57d756863' AND product_name = 'Horse Saddle' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Selle légère pour monter à cheval'
WHERE product_id = 'a6a27433-e7a9-4e78-8ae3-0cb57d756863' AND product_description = 'Lightweight saddle for riding horses' AND product_description_fr IS NULL;
UPDATE products SET product_name_fr = 'Clapier pour lapins'
WHERE product_id = '4affcab7-3ab1-4917-a114-2b6301aa5565' AND product_name = 'Rabbit Hutch' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Clapier extérieur en bois pour lapins'
WHERE product_id = '4affcab7-3ab1-4917-a114-2b6301aa5565' AND product_description = 'Outdoor wooden hutch for rabbits' AND product_description_fr IS NULL;
UPDATE products SET product_name_fr = 'Chauffe-eau pour aquarium'
WHERE product_id = '1501f30e-1db1-44b2-a555-bca6f64450e4' AND product_name = 'Fish Tank Heater' AND product_name_fr IS NULL;
UPDATE products SET product_description_fr = 'Chauffe-eau submersible pour aquariums de poissons tropicaux'
WHERE product_id = '1501f30e-1db1-44b2-a555-bca6f64450e4' AND product_description = 'Submersible heater for tropical fish tanks' AND product_description_fr IS NULL;

CREATE TABLE IF NOT EXISTS product_types
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type_id VARCHAR(36) NOT NULL UNIQUE,
    type_name       TEXT
);

CREATE TABLE IF NOT EXISTS product_ratings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  VARCHAR(36) NOT NULL,
    customer_id VARCHAR(36) NOT NULL,
    rating      SMALLINT,
    review      TEXT
);

CREATE TABLE IF NOT EXISTS product_bundles
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id            VARCHAR(36) NOT NULL UNIQUE,
    bundle_name          TEXT,
    bundle_description   TEXT,
    /* TODO: in the future use a seperate table to store product bundles products */
    product_ids          TEXT[],
    original_total_price DOUBLE PRECISION,
    bundle_price         DOUBLE PRECISION
);

/* TEMPORARY */
CREATE TABLE IF NOT EXISTS images
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id   TEXT,
    image_name TEXT,
    image_type TEXT,
    image_data BYTEA
);