CREATE TABLE IF NOT EXISTS products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          VARCHAR(36) NOT NULL UNIQUE,
    image_id            VARCHAR(36),
    product_name        TEXT,
    product_description TEXT,
    product_sale_price  DOUBLE PRECISION,
    average_rating      DOUBLE PRECISION,
    request_count       INTEGER,
    product_quantity    INTEGER,
    is_unlisted         BOOLEAN,
    product_type        TEXT,
    product_type_id     VARCHAR(36),
    release_date        DATE,
    product_status      TEXT,
    delivery_type       TEXT
);

CREATE TABLE IF NOT EXISTS product_types
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type_id VARCHAR(36) NOT NULL UNIQUE,
    type_name       TEXT
);

CREATE TABLE IF NOT EXISTS product_ratings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  VARCHAR(36) NOT NULL,
    customer_id VARCHAR(36) NOT NULL,
    rating      SMALLINT,
    review      TEXT
);

CREATE TABLE IF NOT EXISTS product_bundles
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id            VARCHAR(36) NOT NULL UNIQUE,
    bundle_name          TEXT,
    bundle_description   TEXT,
    /* TODO: in the future use a seperate table to store product bundles products */
    product_ids          TEXT[],
    original_total_price DOUBLE PRECISION,
    bundle_price         DOUBLE PRECISION
);

/* TEMPORARY */
CREATE TABLE IF NOT EXISTS images
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id   TEXT,
    image_name TEXT,
    image_type TEXT,
    image_data BYTEA
);