name: ASP.NET

on:
  push:
    branches:
      - main
      - bug/VIST-CPC-1267_Missing/Incorrect_docker_compose_and_CI_Configuration_For_Emailing_Service # For TESTING
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Your_password123
          MYSQL_DATABASE: MyAppDb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Restore the dependencies
      - name: Restore dependencies
        run: dotnet restore ./emailing-service/emailing-service.sln

      # Build the project
      - name: Build
        run: dotnet build ./emailing-service/emailing-service.sln --no-restore --configuration Release

      # Run the tests
      - name: Test
        run: dotnet test ./emailing-service/emailing-service-test/emailing-service-test.csproj --no-build --verbosity normal

      # Publish the results (optional)
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./TestResults
