name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          echo "SMTP_PASS=fakepass" > mailer.env
      - name: Build and up the docker
        run: docker-compose up --build
      - name: Down the containers
        run: docker-compose down
      
