name: Docker Compose Actions Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          echo "SMTP_PASS=fakepass" > mailer.env
      - name: Build and up the docker
        run: docker-compose up --abort-on-container-exit
      - name: Down the containers
        run: docker-compose down
      
