name: Is PR Mergable Today?

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  block:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    steps:
      - uses: yykamei/block-merge-based-on-time@main
        id: block
        with:
          timezone: "UTC-4"
          after: 00:00
          before: 00:00
          base-branches: "(default)"
          prohibited-days-dates: "2025-09-29, 2025-10-15, 2025-10-27"
      - run: echo pr-blocked=${{ steps.block.outputs.pr-blocked }}
        if: github.event_name == 'pull_request'
